config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end

  namespace :admin do
    resources :articles
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController

  def index
     @articles = Article.all
  end

  def destroy
    article = Article.find(params["id"])
    article.delete
    redirect_to articles_path
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params["id"])
  end

  def new
    @article = Article.new()
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @article = Article.find(params["article_id"])
    @comments = @article.comments
  end

  def new
    @article = Article.find(params["article_id"])
    @comment = Comment.new()
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save!
      redirect_to article_path(@comment.article)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:article_id, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/admin/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="article-name">
    Name: <%= link_to article.title, article_path(article) %>
    <%= link_to "Comment on this article", new_article_comment_path(article) %>
    <%= link_to 'Delete', admin_article_path(article), method: :delete %>
  </div>
<% end %>

<br>
<br>
<%= link_to "Create a new article", new_article_path() %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="article-name">
    Name: <%= link_to article.title, article_path(article) %>
    <%= link_to "Comment on this article", new_article_comment_path(article) %>
  </div>
<% end %>

<br>
<br>
<%= link_to "Create a new article", new_article_path() %>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
You are viewing article ID: <%= @article.id %>
<%= link_to "View article comments", article_comments_path(@article) %>

app/views/comments/index.html.erb
<div>
  <% @comments.each do |com| %>
  <h4> COMMENT <%= com.id %></h4>
    <%= com.text %>
  <% end %>
<div>

app/views/comments/new.html.erb
<%= form_for [:article, @comment] do |f| %>
  <%= f.text_field :text %>
  <%= f.hidden_field :article_id, value: @article.id %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Back to main page", articles_path %>
    <br>
    <br>
    <%= yield %>
  </body>
</html>